title: Hamburglar Renovation
# author: Kendra Curtis
# email: kscurtis2000+w@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I recently bought a 1971 four level split and in HDTV style, I have named it the "Hamburglar House".
  Most of the house was in orginal condition. I gutted the house.... then COVID happened... so I did a lot
  of the work on the house myself with some help from my Mom and Friends. Here are my some of my renovation adventures!

# social links
# github_username:  kendracurtis # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
